version: 2

# The following stanza defines a map named defaults with a variable that may be
# inserted using the YAML merge (<<: *) key later in the file to save some
# typing. See http://yaml.org/type/merge.html for details.
defaults: &defaults
  environment:
    CI_SCRIPTS: "npx --quiet --package @reactioncommerce/ci-scripts@1.6.2"
    DOCKER_REPOSITORY: "reactioncommerce/reaction"
    DOCKER_NAMESPACE: "reactioncommerce"
    DOCKER_NAME: "reaction"
  docker:
    - image: circleci/node:14.18.1-stretch


install_pnpm: &install_pnpm
  - run:
      name: Install pnpm package manager
      command: sudo npm i -g pnpm@7
  - run:
      name: Check pnpm version
      command: pnpm -v

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - <<: *install_pnpm
      - restore_cache:
          keys:
            - reaction-v6-node-modules-{{ checksum "package.json" }}-{{ checksum "pnpm-lock.yaml" }}
            - reaction-v6-node-modules-{{ .Branch }}
      - run:
          name: Install PNPM dependencies
          command: pnpm install -r
      - save_cache:
          key: reaction-v6-node-modules-{{ checksum "package.json" }}-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
            - packages
      - save_cache:
          key: reaction-v6-node-modules-{{ .Branch }}
          paths:
            - node_modules
            - packages

  dockerfile-lint:
    <<: *defaults
    steps:
      - checkout
      - <<: *install_pnpm
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Lint Dockerfiles
          command: ${CI_SCRIPTS} lint-dockerfiles
  eslint:
    <<: *defaults
    steps:
      - checkout
      - <<: *install_pnpm
      - restore_cache:
          keys:
            - reaction-v6-node-modules-{{ checksum "package.json" }}-{{ checksum "pnpm-lock.yaml" }}
            - reaction-v6-node-modules-{{ .Branch }}
      - run:
          name: Lint JavaScript
          command: pnpm run lint

  graphql-lint:
    <<: *defaults
    steps:
      - checkout
      - <<: *install_pnpm
      - restore_cache:
          keys:
            - reaction-v6-node-modules-{{ checksum "package.json" }}-{{ checksum "pnpm-lock.yaml" }}
            - reaction-v6-node-modules-{{ .Branch }}
      - run:
          name: Lint GraphQL schemas
          command: pnpm -r run lint:gql

  test-unit:
    <<: *defaults
    steps:
      - checkout
      - <<: *install_pnpm
      - restore_cache:
          keys:
            - reaction-v6-node-modules-{{ checksum "package.json" }}-{{ checksum "pnpm-lock.yaml" }}
            - reaction-v6-node-modules-{{ .Branch }}
      - run: pnpm install -r
      - run:
          name: Test Unit
          command: pnpm test

  test-integration-query:
    <<: *defaults
    docker:
      - image: circleci/node:14.18.1-stretch
      # Integration tests need MongoDB server running and accessible on port 27017
      - image: circleci/mongo:4.0.0
        command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
        ports:
          - "27017:27017"
    steps:
      - checkout
      - <<: *install_pnpm
      - restore_cache:
          keys:
            - reaction-v6-node-modules-{{ checksum "package.json" }}-{{ checksum "pnpm-lock.yaml" }}
            - reaction-v6-node-modules-{{ .Branch }}
      - run: pnpm install -r
      - run:
          name: Run Integration Query Tests
          environment:
            MONGO_URL: mongodb://localhost:27017/test
            MONGO_USE_UNIFIED_TOPOLOGY: false
          command: |
            sudo apt-get install -y mongodb
            mongo --eval "rs.initiate()"
            pnpm run test:integration:query

  test-integration-mutation:
    <<: *defaults
    docker:
      - image: circleci/node:14.18.1-stretch
      # Integration tests need MongoDB server running and accessible on port 27017
      - image: circleci/mongo:4.0.0
        command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
        ports:
          - "27017:27017"
    steps:
      - checkout
      - <<: *install_pnpm
      - restore_cache:
          keys:
            - reaction-v6-node-modules-{{ checksum "package.json" }}-{{ checksum "pnpm-lock.yaml" }}
            - reaction-v6-node-modules-{{ .Branch }}
      - run: pnpm install -r
      - run:
          name: Run Integration Mutation Tests
          environment:
            MONGO_URL: mongodb://localhost:27017/test
            MONGO_USE_UNIFIED_TOPOLOGY: false
          command: |
            sudo apt-get install -y mongodb
            mongo --eval "rs.initiate()"
            pnpm run test:integration:mutation

  release:
    <<: *defaults
    steps:
      - checkout
      - <<: *install_pnpm
      - restore_cache:
          keys:
            - reaction-v6-node-modules-{{ checksum "package.json" }}-{{ checksum "pnpm-lock.yaml" }}
            - reaction-v6-node-modules-{{ .Branch }}
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - run:
          name: Push the latest version to npm
          command: pnpm publish -r

  docker-build-push:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push production Docker image
          command: |
            VERSION=$(git describe --tags `git rev-list --tags --max-count=1` | cut -c2-100)
            docker build -t ${DOCKER_REPOSITORY}:${VERSION} -t ${DOCKER_REPOSITORY}:latest ./apps/reaction
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker push ${DOCKER_REPOSITORY}:${VERSION}
            docker push ${DOCKER_REPOSITORY}:latest

workflows:
  version: 2
  build_and_test:
    jobs:
      - install-dependencies
      - dockerfile-lint:
          requires:
            - install-dependencies
      - eslint:
          requires:
            - install-dependencies
      - graphql-lint:
          requires:
            - install-dependencies
      - test-unit:
          requires:
            - install-dependencies
      - test-integration-query:
          requires:
            - install-dependencies
      - test-integration-mutation:
          requires:
            - install-dependencies
      - release:
          filters:
            branches:
              only:
                - trunk
          requires:
            - dockerfile-lint
            - eslint
            - graphql-lint
            - test-unit
            - test-integration-query
            - test-integration-mutation
      - docker-build-push:
          context: reaction-publish-docker
          filters:
            branches:
              only:
                - trunk
          requires:
            - release
